name: Deploy test version of Simplio app v2 to AppStore and GooglePlay

on:
  push:
    branches:
#      - 'feature/*'
      - 'master'

jobs:
  run-tests:
#    if: "!contains(github.event.commits[0].message, '[automated commit]')"
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@feature/initial-infrastructure
    with:
      e2e: true

#  increase-version:
#    needs: [run-tests]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_increase_version.yml@feature/initial-infrastructure
#    secrets:
#      GIT_TOKEN: '${{ secrets.GIT_TOKEN }}'


  build-ios:
#    if: "contains(github.event.commits[0].message, '[automated commit]')"
    needs: [run-tests]
    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_ios.yml@feature/initial-infrastructure
    with:
      environment: 'dev'
    secrets:
      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
      DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
      DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
      FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
      PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
      TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
      TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'

  build-android:
#    if: "contains(github.event.commits[0].message, '[automated commit]')"
    needs: [run-tests]
    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_android.yml@feature/initial-infrastructure
    secrets:
      ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
    with:
      environment: 'dev'
